### ISSUE TITLE
some modules missing

### ISSUE THREAD

**Issue by SunHaozhe** [yongxuUSTC/aDAE_DNN_audio_tagging#1]
It seems that some modules like config_dae are missing, which are necessary to run the code. Why did you remove them ?

**Comment by yongxuUSTC** [comment]
Hi,

This code is not maintained anymore, because it previously depends on an abandoned library.
Our better audio tagging code is here: https://github.com/yongxuUSTC/dcase2017_task4_cvssp
Which helped us to achieve the 1st rank in DCASE2017.

Thanks
yong

**Comment by SunHaozhe** [comment]
Thanks for your reply.
